repos:

# do not pass files to ansible-lint, see:
# https://github.com/ansible/ansible-lint/issues/611
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.7
  hooks:
    - id: ansible-lint
      name: Lint Ansible
      entry: ansible-lint --force-color ./ansible
      pass_filenames: false

- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: shellcheck
    name: Lint Shell Scripts

- repo: https://github.com/yelp/detect-secrets.git
  rev: v0.14.3
  hooks:
  -   id: detect-secrets
      name: Detect Secrets (Yelp)
      args: ['--baseline', '.secrets.baseline']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
