repos:

- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: shellcheck
    name: Lint shell scripts

- repo: https://github.com/yelp/detect-secrets.git
  rev: v0.14.3
  hooks:
  -   id: detect-secrets
      name: Detect secrets
      args: ['--baseline', '.secrets.baseline']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
